name: container
on: pull_request

jobs:
  node_docker:
    runs-on: ubuntu-latest
    services:
      app:
        image: alialaa17/node_api
        ports:
          - 3001:3000
      mongo:
        image: mongo
        ports:
          - 27017:27017
    container:
        image: node:13.5.0-alpine3.10
    steps:
      - name: Post a user
        run : " curl -X POST http://localhost:3001/api/user -H 'Content-Type: application/json -d'  '{\"username\": \"hello\", \"address\": \"dwded\" }'"
      - name: Get Users
        run: curl http://localhost:3001/api/user